### ISSUE TITLE
/appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead.

### ISSUE THREAD

**Issue by mentastic** [digital-blueprint/webapppassword#145]
## Explain the Problem
What problem did you encounter?
The log runs full with this message:
/appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead.

## Steps to Reproduce
Explain what you did to encounter the issue
1. Install/ having installed webapppassword in nextcloud instance
2. Just look into the log of nextcloud instance with an admin account

## System Information
* WebAppPassword app version: 23.12.0
* Nextcloud version: 28.0.1
* Cron type: Cron
* PHP version: 8.1.2
* Database and version: MariadB v20.6
* Browser and version: Firefox v120.0.1
* Distribution and version: Ubuntu 22.04 LTS

## Contents of nextcloud/data/nextcloud.log

```json
{"reqId":"qi8FChlGBRXpX15Q21m8","level":0,"time":"2023-12-27T13:31:03+00:00","remoteAddr":"","user":"--","app":"webapppassword","method":"","url":"--","message":"/appinfo/app.php is dep
recated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"--","version":"28.0.1.1","data":{"app":"webapppassword"}}
```

## Contents of Browser Error Console
No need.

**Comment by pbek** [comment]
Thank you for reporting.

**Comment by pbek** [comment]
Note: you need to set the `loglevel` to 0 in your Nextcloud's `config.php` to be able to reproduce this! It's on 2 by default!

**Comment by pbek** [comment]
## 24.1.0
- Fixed `app.info` deprecation warning debug message
  (for [#145](https://github.com/digital-blueprint/webapppassword/issues/145)

There now is a new release, could you please test it and report if it works for you?

**Comment by mentastic** [comment]
> ## 24.1.0
> 
>     * Fixed `app.info` deprecation warning debug message
>       (for [#145](https://github.com/digital-blueprint/webapppassword/issues/145))
> 
> 
> There now is a new release, could you please test it and report if it works for you?

now everything's well, thanx

**Comment by mentastic** [comment]
problem is fixed

**Comment by pbek** [comment]
Great, thank you for testing!
