### ISSUE TITLE
OC\AppFramework\Utility\QueryNotFoundException: Could not resolve OCA\WebAppPassword\Controller\PreviewController! Class "OCA\WebAppPassword\Controller\PreviewController" does not exist

### ISSUE THREAD

**Issue by Daxiongmao87** [digital-blueprint/webapppassword#149]
## Explain the Problem
What problem did you encounter?
Error 500 when making api call for index.php/apps/ webapppassword/core/preview

## Steps to Reproduce
Explain what you did to encounter the issue
1. api call using fetch with GET method in javascript using the following endpoint and parameters: 'index.php/apps/webapppassword/core/preview?fileId=###;

## System Information
* WebAppPassword app version: 24.1.0
* Nextcloud version: 27.1.2
* Cron type: local
* PHP version: 8.2.11
* Database and version: mysql v11.2.2
* Browser and version: firefox 118.0.1
* Distribution and version: Client: Ubuntu Budgie 23.10, Server: Debian 12

## Contents of nextcloud/data/nextcloud.log

```json
	OC\AppFramework\Utility\QueryNotFoundException: Could not resolve OCA\WebAppPassword\Controller\PreviewController! Class "OCA\WebAppPassword\Controller\PreviewController" does not exist

    /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php - line 142:

    OC\AppFramework\Utility\SimpleContainer->resolve("OCA\\WebApp ... r")

    /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 494:

    OC\AppFramework\Utility\SimpleContainer->query("OCA\\WebApp ... r")

    /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 466:

    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OCA\\WebApp ... r")

    /var/www/html/lib/private/AppFramework/App.php - line 162:

    OC\AppFramework\DependencyInjection\DIContainer->query("OCA\\WebApp ... r")

    /var/www/html/lib/private/Route/Router.php - line 315:

    OC\AppFramework\App::main("OCA\\WebApp ... r", "preflightedCors", [ "OC\\AppFr ... "], [ "webapppas ... "])

    /var/www/html/lib/base.php - line 1068:

    OC\Route\Router->match("/apps/webap ... w")

    /var/www/html/index.php - line 36:

    OC::handleRequest()
```

## Contents of Browser Error Console
Read http://ggnome.com/wiki/Using_The_Browser_Error_Console if you are unsure what to put here

```
XHROPTIONS
https://nextcloudserver.example/index.php/apps/webapppassword/core/preview?fileId=167981
CORS Preflight Did Not Succeed

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://nextcloudserver.example/index.php/apps/webapppassword/core/preview?fileId=167981. (Reason: CORS preflight response did not succeed). Status code: 500.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://nextcloudserver.example/index.php/apps/webapppassword/core/preview?fileId=167981. (Reason: CORS request did not succeed). Status code: (null).
```

**Comment by Daxiongmao87** [comment]
Nevermind, I believe this is just a feature that's yet to be implemented, if I go by reading this: https://github.com/digital-blueprint/webapppassword/issues/65

**Comment by pbek** [comment]
I almost feared this came from https://github.com/digital-blueprint/webapppassword/commit/28168acd58cee830d291d3bcea736b08b10e37f9 of #145.

@aleixq, do you have the same issue or any issue with preview API?

**Comment by Daxiongmao87** [comment]
If I can provide any other details i'd be more than happy to help. 

The QueryNotFoundException error has me curious since it seems to look for a controller class that does not exist in webapppasswords lib/Controller folder.

I assume the intent was to either pass the endpoint to the core version of PreviewController, either through extending the class or some other method?

**Comment by pbek** [comment]
Does the WebAppPassword admin page still work for you?

**Comment by Daxiongmao87** [comment]
It does, I am able to enter my domain in all three fields

**Comment by pbek** [comment]
Then I don't think anything got broken in the current release.

**Comment by pbek** [comment]
Let's wait for @aleixq.

**Comment by Daxiongmao87** [comment]
adding this class under lib/PreviewController.php fixes my issue:

`<?php

declare(strict_types=1);

namespace OCA\WebAppPassword\Controller;

use OC\Core\Controller\PreviewController as CorePreviewController;
use OCP\IPreview;
use OCP\Files\IRootFolder;
use OCP\IRequest;
use OCP\AppFramework\Http;
use OCP\AppFramework\Http\Response;

class PreviewController extends CorePreviewController {
    use AccessControl;

    public function __construct(
        string $appName,
        IRequest $request,
        IPreview $preview,
        IRootFolder $root,
        ?string $userId
    ) {
        // Call the parent constructor with the provided arguments
        parent::__construct($appName, $request, $preview, $root, $userId);
    }

	/**
	 * @NoAdminRequired
	 * @NoCSRFRequired
	 *
	 * @return DataResponse|FileDisplayResponse
	 */
    public function getPreviewByFileId(
        int $fileId = -1,
        int $x = 32,
        int $y = 32,
        bool $a = false,
        bool $forceIcon = true,
        string $mode = 'fill'
    ) DataResponse|FileDisplayResponse {
        $response = parent::getPreviewByFileId($fileId, $x, $y, $a, $forceIcon, $mode);
        return $this->checkPreviewOrigin($response);
    }
   
}`

**Comment by pbek** [comment]
Thank you, I can take a look next week.
I wonder why it wasn't necessary before.
But I only checked if #94 will break existing stuff. 😁

**Comment by Daxiongmao87** [comment]
No problem! I'm not sure either, I just started using the application for my needs, so no idea that it worked earlier, and don't know too much about php in general.  Wish I could provide some insight.

**Comment by aleixq** [comment]
I am looking too, will answer asap

**Comment by aleixq** [comment]
I am trying to understand what happens in last release, but preview feature needs this controller:

```
<?php

declare(strict_types=1);
// SPDX-FileCopyrightText: Aleix Quintana Alsius <kinta@communia.org>
// SPDX-License-Identifier: AGPL-3.0-or-later

namespace OCA\WebAppPassword\Controller;

use OC\Core\Controller\PreviewController as CorePreviewController;
use OCP\AppFramework\Http\DataResponse;

class PreviewController extends CorePreviewController
{
    use AccessControl;

    /**
     * @NoAdminRequired
     *
     * @NoCSRFRequired
     *
     * Get a preview by file ID
     *
     * @param int    $fileId    ID of the file
     * @param int    $x         Width of the preview
     * @param int    $y         Height of the preview
     * @param bool   $a         Whether to not crop the preview
     * @param bool   $forceIcon Force returning an icon
     * @param string $mode      How to crop the image
     *
     * @return FileDisplayResponse<Http::STATUS_OK, array{Content-Type: string}>|DataResponse<Http::STATUS_BAD_REQUEST|Http::STATUS_FORBIDDEN|Http::STATUS_NOT_FOUND, array<empty>, array{}>
     *
     * 200: Preview returned
     * 400: Getting preview is not possible
     * 403: Getting preview is not allowed
     * 404: Preview not found
     */
    public function getPreviewByFileId(
        int $fileId = -1,
        int $x = 32,
        int $y = 32,
        bool $a = false,
        bool $forceIcon = true,
        string $mode = 'fill'
    ) : DataResponse|FileDisplayResponse
    {
        $response = parent::getPreviewByFileId(...func_get_args());

        return $this->checkPreviewOrigin($response);
    }
}
```

I have it on my instance so maybe this feature never worked as it should...  But It surprises me that nobody needs it in a year... so I 'll re-assert that there was such file absence .

@Daxiongmao87 now that you are testing with 27 version,  could you please check if there aren't CORS problems with your (or my)  controller? 


I have to look deeper but with my 28 nc it's not working as the core controller is not providing the necessary preflightedCors method as this is not using the apicontroller or the ocscontroller, instead it uses a simple controller without the cors annotation processor.

In my case, to get it working, I need this controller found in this predraft PR fork:
https://github.com/aleixq/webapppassword/blob/preview-28/lib/Controller/PreviewController.php
Which includes the changes in preview controller for nc 28 (mimefallback parameter),  and the important preflightedCors.

**Comment by Daxiongmao87** [comment]
Hey @aleixq I am indeed not having any cors issues after implementing my controller.  I originally was getting cors issues and that was where my investigation started.  I discovered a few misconfigurations on my nginx server, and once those were resolved, that's when I started seeing my error 500 returns.

After spending some time trying to validate the missing controller, that's when I posted here.

**Comment by pbek** [comment]
@aleixq, did you ever create a pr for that controller? It wasn't in your pr back then, was it?

**Comment by aleixq** [comment]
I was surprised with that but it wasn't in the pr despite the file is in my local tree as untracked file...

**Comment by pbek** [comment]
> I am trying to understand what happens in last release, but preview feature needs this controller:

In the last release, only the `app.php` was removed, because NC is complaining about it since (I guess) 27.

**Comment by pbek** [comment]
> I was surprised with that but it wasn't in the pr, despite the file is in my local tree (as untracked file...)

Just create a new PR then 😉

**Comment by aleixq** [comment]
Ok, but a few questions. 
Do you want that this controller adds the new attribute together with annotations?
This will be for nextcloud 28 and I don't know how previous nextcloud versions treat these new use statements:
as in https://docs.nextcloud.com/server/latest/developer_manual/basics/controllers.html#reading-and-writing-session-variables 


Also, as the controller is extended from this abstract it needs different parameters for 27 and 28:

https://github.com/nextcloud/server/commit/28725c46a84db6e733c42e38cbc5e1b7f0e3854b#diff-5b14b6adeeb46970e6a2a91d54d0c4f2e41a36eabe8d6287bd3b1bfd94b89977L144

how is this release marked as for great than 28 and not for previous of 27?

**Comment by Daxiongmao87** [comment]
Yeah as I was writing the PreviewController, I also noticed that Nextcloud 28's PreviewController is a bit different from 27's, such as 28 requiring IMimeIconProvider.

Considering 28 isn't released yet, and this missing PreviewController is causing functionality issues with the preview part of the api, do you all want to release something like a fix for now, but also work on the 28 preview for when that releases?

I think this [is the moment of the IMimeIconProvider addition](https://github.com/nextcloud/server/commit/28725c46a84db6e733c42e38cbc5e1b7f0e3854b#diff-5b14b6adeeb46970e6a2a91d54d0c4f2e41a36eabe8d6287bd3b1bfd94b89977).

**Comment by pbek** [comment]
> how is this release marked as for great than 28 and not for previous of 27?

What release? webapppassword? it should work for both 27 and 28!

> Considering 28 isn't released yet

NC 28 was released a few weeks ago, wasn't it 😉

**Comment by Daxiongmao87** [comment]
> > how is this release marked as for great than 28 and not for previous of 27?
> 
> What release? webapppassword? it should work for both 27 and 28!
> 
> > Considering 28 isn't released yet
> 
> NC 28 was released a few weeks ago, wasn't it 😉

Ah you are right! I apologize.  Let me know if you all need anything from me!

**Comment by pbek** [comment]
## 24.1.1
- The missing controller for the Preview API was added
  (for [#149](https://github.com/digital-blueprint/webapppassword/issues/149))

There now is a new release, could you please test it and report if it works for you?

**Comment by Daxiongmao87** [comment]
this seems to be working for me with the recent updates (thank you both), i can close if youd like

**Comment by pbek** [comment]
Great, thank you for testing!
