### ISSUE TITLE
Please clarify any security concerns in using this app

### ISSUE THREAD

**Issue by sunjam** [digital-blueprint/webapppassword#2]
Hi, hoping documentation for the app can be clarified on security implications in using this app as mentioned on [this thread](https://github.com/nextcloud/server/issues/3131).  Thanks!

**Comment by pbek** [comment]
Well, those are the lines that are most important to understand, so you can assess the risk:

https://github.com/digital-blueprint/webapppassword/blob/7cb3cd468bc21b655aba18a4e526087b3f537c59/lib/Connector/Sabre/CorsPlugin.php#L36-L61

**Comment by sunjam** [comment]
Truthfully, I do not understand after reading this code.  Thanks.

**Comment by pbek** [comment]
The HTTP headers, that are set are the important part.
