### ISSUE TITLE
File Sharing API seems to break whole app in Nextcloud 29.0.2

### ISSUE THREAD

**Issue by pbek** [digital-blueprint/webapppassword#200]
@aleixq

With Nextcloud 29.0.2 the PHP API in the Nextcloud server got breaking changes that seems to break the whole app via `ShareAPIController::createShare`.

https://github.com/nextcloud/server/commit/5dbb96fc8a64fb6469aa085b27f80338e665538e

When using WebAppPassword for creating temporary app passwords, this causes:

```json
{
    "reqId": "MeFUfsLGC1ozQWskec9c",
    "level": 3,
    "time": "June 18, 2024 11:13:39",
    "remoteAddr": "10.13.128.116",
    "user": "--",
    "app": "PHP",
    "method": "GET",
    "url": "/index.php/apps/webapppassword?target-origin=https%3A%2F%2Fdbp-dev.tugraz.at%2Fapps%2Fsignature%2Fde%2Fqualified-pdf-upload",
    "message": "Declaration of OCA\\WebAppPassword\\Controller\\ShareAPIController::createShare(?string $path = null, ?int $permissions = null, int $shareType = -1, ?string $shareWith = null, string $publicUpload = 'false', string $password = '', ?string $sendPasswordByTalk = null, string $expireDate = '', string $note = '', string $label = '', ?string $attributes = null): OCP\\AppFramework\\Http\\DataResponse must be compatible with OCA\\Files_Sharing\\Controller\\ShareAPIController::createShare(?string $path = null, ?int $permissions = null, int $shareType = -1, ?string $shareWith = null, string $publicUpload = 'false', string $password = '', ?string $sendPasswordByTalk = null, ?string $expireDate = null, string $note = '', string $label = '', ?string $attributes = null): OCP\\AppFramework\\Http\\DataResponse at /home/nc/pers/apps/webapppassword/lib/Controller/ShareAPIController.php#34",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "version": "29.0.2.2",
    "data": {
        "app": "PHP"
    }
}
```

**Comment by pbek** [comment]
There are backports of those breaking changes in Nextcloud Server to 28 and below too...

I'll try to introduce a workaround hat might work in 29.0.1 and 29.0.2 and probably also in Nextcloud 28.

**Comment by pbek** [comment]
## 24.6.0
- Fixed breaking change introduced in Nextcloud 29.0.2

**Comment by pbek** [comment]
For this issue, I created a workaround, but I don't know if the sharing API works at all now after the changes in Nextcloud 29.0.2. And #197 is also still open... 😉

**Comment by pbek** [comment]
@aleixq, @lazka 
There now is a new release, could you please test it and report if it works for you?

**Comment by lazka** [comment]
I can confirm that the new releases fixes the app in general, no idea about file shares.

**Comment by pbek** [comment]
Thank you for testing.
