### ISSUE TITLE
 Update app for Nextcloud 30

### ISSUE THREAD

**Issue by pbek** [digital-blueprint/webapppassword#226]
It would be great to update the app for Nextcloud 30 before it is released.

**Comment by pbek** [comment]
@DanRiess, @aleixq, the share API is breaking the whole app in Nextcloud 30 (again)! 😬

**Comment by aleixq** [comment]
It was already previewed in https://github.com/digital-blueprint/webapppassword/pull/214#issuecomment-2282859508 . The parameters are not matching because there are new services injected in https://github.com/nextcloud/server/blob/82d2ec09311a2db13edd7eb407629d03333037c1/apps/files_sharing/lib/Controller/ShareAPIController.php#L89C1-L90C27 :

```
		private IProviderFactory $factory,
		private IMailer $mailer,
```
So It must be added in our controller implementation and add (another) conditional for versions from 30 in https://github.com/digital-blueprint/webapppassword/pull/214/files#diff-f595b0984308dfb3189a2936677149ee97855b02d94febfd9195f6a005ddb4b3R64


I'll try to write the code later and check it out in my nc 30 version.

**Comment by pbek** [comment]
Great, because I need to do a new release for Nextcloud 30, but I can wait until tomorrow. 😉

**Comment by aleixq** [comment]
This works in v30, and should work in <30 (but not tested) @DanRiess may check it in its version... :
```patch
--- ShareAPIController.php      2024-09-16 23:23:21.623891044 +0200
+++ ShareAPIController.php.old  2024-09-16 23:00:56.073165438 +0200
@@ -18,9 +18,7 @@
 use OCP\IRequest;
 use OCP\IURLGenerator;
 use OCP\IUserManager;
-use OCP\Mail\IMailer;
 use OCP\Share\IManager;
-use OCP\Share\IProviderFactory;
 use OCP\UserStatus\IManager as IUserStatusManager;
 use Psr\Container\ContainerInterface;
 use Psr\Log\LoggerInterface;
@@ -49,8 +47,6 @@
                private IPreview $previewManager,
                private IDateTimeZone $dateTimeZone,
                private LoggerInterface $logger,
-               private IProviderFactory $factory,
-               private IMailer $mailer,
                IUserSession $userSession,
        ) {
                // In an options request, $user will be null, as there is no Auth header to get data from.
@@ -64,11 +60,8 @@
                // Call the constructor.
                // The paremeter order is different between versions, this has to be accounted for.
                // Version string is identical for 27.1.10.1 and 27.1.10.2.
-               $int_version = OC_Util::getVersion();
-               if ($int_version[0] > 29) {
-                       parent::__construct($AppName, $request, $shareManager, $groupManager, $userManager, $rootFolder, $urlGenerator, $l, $config, $appManager, $serverContainer, $userStatusManager, $previewManager, $dateTimeZone, $logger, $factory, $mailer, $uid);
-               }
-               else if ($int_version[0] == 27 and $int_version[1] == 1 and $int_version[2] ==  '10') {
+               $version = OC_Util::getVersionString();
+               if ($version == '27.1.10') {
                        parent::__construct($AppName, $request, $shareManager, $groupManager, $userManager, $rootFolder, $urlGenerator, $uid, $l, $config, $appManager, $serverContainerOld, $userStatusManager, $previewManager, $dateTimeZone);
                } else {
                        parent::__construct($AppName, $request, $shareManager, $groupManager, $userManager, $rootFolder, $urlGenerator, $l, $config, $appManager, $serverContainer, $userStatusManager, $previewManager, $dateTimeZone, $logger, $uid);
@@ -104,8 +97,7 @@
                ?string $expireDate = null,
                string $note = '',
                string $label = '',
-               ?string $attributes = null,
-               ?string $sendMail = null
+               ?string $attributes = null
        ): DataResponse {
                $response = parent::createShare(...func_get_args());
 
@@ -228,8 +220,7 @@
                string $note = null,
                string $label = null,
                string $hideDownload = null,
-               string $attributes = null,
-               ?string $sendMail = null
+               string $attributes = null
        ): DataResponse {
                $response = parent::updateShare(...func_get_args());
 

```

I'll create PR tomorrow if nobody works on it to merge it faster.

**Comment by DanRiess** [comment]
I currently don't have the time to test this, but the code looks good. I believe this should work fine.

**Comment by pbek** [comment]
Thank you, I'll test with NC29 and NC30.

**Comment by pbek** [comment]
I'll try to recreate what you did, because your patch can't be applied... 😬

**Comment by pbek** [comment]
If tested, if the password- and WebDAV API worked in Nextcloud 28, Nextcloud 29 and Nextcloud 30. At least the Nextcloud instance is usable when the app in installed.

I really am not fond of the sharing API breaking so much between and at version changes. 😬

**Comment by pbek** [comment]
## 24.9.0
- Updated and tested app for Nextcloud 30 (for [#226](https://github.com/digital-blueprint/webapppassword/issues/226))
    - Nextcloud instance breaking changes in the sharing API were fixed

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
