### ISSUE TITLE
Access-Control-Allow-Credentials header is missing

### ISSUE THREAD

**Issue by powerflo** [digital-blueprint/webapppassword#6]
I want to use https://diffuse.sh to listen to music stored in my Nextcloud.

WebAppPassword is configured to allow diffuse.sh as an origin. But still the following error is shown in the browser:

> Access to fetch at 'https://.../remote.php/dav/files/florian/Music/The%20Beatles/Live%20at%20the%20BBC/1-01%20Beatles%20Greetings%20(Spoken%20Word)%20%5BLive%20at%20the%20BBC%20For%20_The%20Public%20Ear_%203rd%20November%2C%201963%5D.m4a' from origin 'https://diffuse.sh' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'.

**Comment by pbek** [comment]
Go ahead, make your PR. 😁

**Comment by pbek** [comment]
I merged it into https://gitlab.tugraz.at/dbp/nextcloud/webapppassword.
